version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DRUPAL_VERSION: V8
    steps:
      - checkout
      - run:
          name: "Setup variables"
          command: |
            echo $CIRCLE_BRANCH
      - run:
          name: Install DKTL
          command: |
            cd ~
            git clone https://github.com/GetDKAN/dkan-tools.git
            cd dkan-tools
            git checkout cra-switch
            cd ../
            chmod 777 ./dkan-tools/bin/dktl
            export PATH=$PATH:~/dkan-tools/bin
            which dktl
      - run:
          name: Set up dirs
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ..
            mv project frontend
            mkdir project
      - run:
          name: Create DKAN site with frontend; run tests
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            dktl init --dkan=dev-add-cra-config
            dktl make
            dktl install
            dktl install:sample
            mv ../frontend src
            dktl frontend:install
            dktl frontend:build
            dktl dkan:test-cypress frontend
      - store_artifacts:
          path: src/frontend/cypress/screenshots
      - store_artifacts:
          path: src/frontend/cypress/videos
