version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DRUPAL_VERSION: V8
    steps:
      - checkout
      - run:
          name: "Setup variables"
          command: |
            echo $CIRCLE_BRANCH
      - run:
          name: Install DKTL
          command: |
            git clone --branch=dan-refactor --depth 1 https://github.com/GetDKAN/dkan-tools.git ~/dkan-tools
            chmod 777 ~/dkan-tools/bin/dktl
            echo "export PATH=~/dkan-tools/bin:$PATH" >> $BASH_ENV
      - run:
          name: Set up dirs
          command: |
            cd .. &&  mv project frontend
            mkdir project
      - run:
          name: Create DKAN site with frontend; run tests
          command: |
            dktl init --dkan=dev-add-cra-config
            dktl make
            dktl install
            dktl install:sample
            mv ../frontend src
            dktl frontend:install
            dktl frontend:build
            dktl dkan:test-cypress frontend
      - store_artifacts:
          path: src/frontend/cypress/screenshots
      - store_artifacts:
          path: src/frontend/cypress/videos
